dist: bitonic
language: cpp
os: linux

env:
  - CMAKE_VERSION=3.16.2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake

compiler:
  - clang

script:
  - cmake .
  - make all